# Generated by Django 6.0 on 2026-09-16 04:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_alter_contactsection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherpage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
