# Generated by Django 6.0.4 on 2026-04-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_created_at_user_updated_at_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='purpose',
            field=models.CharField(choices=[('account_activation', 'Account activation'), ('password_reset', 'Password reset')], default='account_activation', max_length=20),
            preserve_default=False,
        ),
    ]
